# Program synthesis training config

defaults:
- arch: program_synthesis_hrm
- _self_

hydra:
  output_subdir: null

# Data path
data_path: data/program-synthesis-simple-math-final

# Hyperparams - Training (reduced for testing)
global_batch_size: 64

epochs: 1000
eval_interval: 10
checkpoint_every_eval: True

lr: 1e-3
lr_min_ratio: 0.1
lr_warmup_steps: 100

# Standard hyperparameter settings
beta1: 0.9
beta2: 0.95
weight_decay: 0.01

# Puzzle embedding (disabled for program synthesis)
puzzle_emb_lr: 0.0
puzzle_emb_weight_decay: 0.0

# Evaluation outputs to save
eval_save_outputs: ['node_exists', 'node_types', 'adjacency']
